version: "3.9"
services:
  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    restart: unless-stopped
    volumes:
      - sftp_data:/home
      - ./users.conf:/etc/sftp/users.conf:ro
volumes:
  sftp_data: