# Ansible Playbook to setup the Sandbox virtual machine to run on a Ubuntu 20.04 LTS.
#   Run the command: ansible-playbook -i inventory-datacloud.yaml setup-simulator-vm.yaml 

- name: Setup Sandbox VM
  hosts: sandbox-vm
  tasks:
    - name: Run software updates first
      apt:
        # Upgrade the system
        update_cache: yes
        upgrade: full
        # Keep it tidy
        autoclean: yes
        autoremove: yes
    - name: Install packages we like
      apt:
        pkg:
          - htop
          - screen
          - docker.io
          - docker-compose
    - name: Expose Docker Deamon to tcp://0.0.0.0
      lineinfile:
        path: /lib/systemd/system/docker.service
        regexp: '^ExecStart='
        line: ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375 --containerd=/run/containerd/containerd.sock
    - name: SystemD reload
      systemd:
        daemon_reload: true
    - name: Restart Docker Deamon 
      service:
        name: docker
        state: restarted
    - name: Make the SIM-PIPE-Sandbox directory
      file:
        path: /home/ubuntu/SIM-PIPE-Sandbox
        state: directory
    - name: Copy the Docker Compose file
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/SIM-PIPE-Sandbox/docker-compose.yaml
    - name: Copy the users.conf file
      copy:
        src: ./users.conf
        dest: /home/ubuntu/SIM-PIPE-Sandbox/users.conf
    - name: Start the Docker compose
      community.docker.docker_compose:
        project_src: /home/ubuntu/SIM-PIPE-Sandbox
        state: present
      register: output_compose
    - name: Print the output of the compose
      debug:
        var: output_compose
