version: '3.6'

services:
  timescaledb:
    image: timescale/timescaledb:2.5.1-pg14
    restart: unless-stopped
    volumes:
      - db_data1:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TIMESCALEDB_TELEMETRY: "off"
      TS_TUNE_MEMORY: "512MB"

  hasura:
    image: hasura/graphql-engine:v2.1.1.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "timescaledb"
      - "controller"
    restart: unless-stopped
    volumes:
      - ./hasura/migrations:/hasura-migrations:ro
      - ./hasura/metadata:/hasura-metadata:ro
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@timescaledb:5432/postgres
      PG_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@timescaledb:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_LOG_LEVEL: debug
      # REMOTE_SCHEMA_URL: ${REMOTE_SCHEMA_URL}
  controller:
    image: simpipe-backend
    ports:
      - "9000:9000"
      - "2375:2375"
      - "22:22"
    restart: on-failure:2
    volumes:
      - ./controller/simulations:/app/simulations
      - ./controller/uploaded_files:/app/uploaded_files
      - ./controller/log:/log
    environment:
      HASURA: http://hasura:8080/v1/graphql
      HASURA_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}      
      CONTAINER_TIME_LIMIT: ${CONTAINER_TIME_LIMIT}
      CONTAINER_STOP_TIMEOUT : ${CONTAINER_STOP_TIMEOUT}
      POLLING_INTERVAL: ${POLLING_INTERVAL}
      REMOTE_OUTPUT_DIR: 'out/'
      REMOTE_INPUT_DIR: 'in/'
      SANDBOX_IP: ${SANDBOX_IP} 
      # REMOTE_DOCKER: true
      DEF_PIPE_LIST_API: 'https://crowdserv.sys.kth.se/api/repo/'
      DEF_PIPE_PIPELINE_API: 'https://crowdserv.sys.kth.se/api/repo/export/'
      DEF_PIPE_API_PIPELINE: 'https://crowdserv.sys.kth.se/api/repo/export/'

  svelte:
    image: simpipe-frontend   
    ports:
      - "9090:3000"
    depends_on:
      - "controller"   

  converter:
    image: simpipe-converter   
    ports:
      - "9005:9005"    
volumes:
  db_data1:
    null
  appsmith:
    null
