version: '3.6'

services:
  timescaledb:
    image: timescale/timescaledb:2.5.1-pg14
    restart: unless-stopped
    volumes:
      - db_data1:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgrespassword}
      TIMESCALEDB_TELEMETRY: "off"
      TS_TUNE_MEMORY: "512MB"

  hasura:
    image: hasura/graphql-engine:v2.1.1.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "timescaledb"
      - "controller"
    restart: unless-stopped
    volumes:
      - ./hasura/migrations:/hasura-migrations:ro
      - ./hasura/metadata:/hasura-metadata:ro
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD-postgrespassword}@timescaledb:5432/postgres
      PG_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD-postgrespassword}@timescaledb:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET-hasuraadminsecret}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_LOG_LEVEL: debug
      REMOTE_SCHEMA_URL: http://10.218.149.206:9000

  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8085:80"
    depends_on:
      - "hasura"
    restart: unless-stopped
    volumes:
      - appsmith:/appsmith-stacks

  controller:
    image: simpipe-backend
    ports:
      - "9000:9000"
      - "2375:2375"
      - "22:22"
    restart: unless-stopped
    volumes:
      - ./simulations:/simulations
      - ./uploaded_files:/uploaded_files
      - ./log:/log
    env_file:
      - ./controller.env
    #environment:
      # HASURA: http://hasura:8080/v1/graphql
      # SANDBOX_IP: '192.168.56.1'
      # REMOTE_DOCKER: true
      # CONTAINER_TIME_LIMIT: 20
      # CONTAINER_STOP_TIMEOUT: 5
      # POLLING_INTERVAL: 1
      # REMOTE_OUTPUT_DIR: 'out/'
      # REMOTE_INPUT_DIR: 'in/'
      
volumes:
  db_data1:
    null
  appsmith:
    null
