-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "simpipe"."resource_usage" add column "time" timestamp with time zone
--  not null;
