apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    simpipe.sct.sintef.no/project: hello-world
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  entrypoint: asm-hello
  templates:
    - name: asm-hello
      container:
        # We do not pull as we use a local image
        imagePullPolicy: Never
        # Alternatively if you have a registry
        # image: mycluster-registry:54397/hello-world:latest
        # imagePullPolicy: IfNotPresent
        image: hello-world:latest
        command: ["/hello_world"]
