global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  # - job_name: prometheus
  #   static_configs:
  #     - targets: ["localhost:9090"]
  # - job_name: promscale
  #   static_configs:
  #     - targets: ["promscale:9201"]
  - job_name: cadvisor
    static_configs:
      - targets: ["sandbox:8080"]
    # Scrape faster
    scrape_interval: 2s

remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true
