{{- if .Values.controller.virtualization.enabled }}
# Defines a ClusterRole to grant cluster-scoped permissions for simpipe-controller (for VM node virtualization).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "simpipeController.serviceAccountName" . }}-controller-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "delete", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["pods/eviction"]
  verbs: ["create"]
{{- end }}
