{{- if .Values.minio.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpipe-minio
  labels:
    app: simpipe-minio
    {{- include "simpipeUtils.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpipe-minio
  template:
    metadata:
      labels:
        app: simpipe-minio
    spec:
      containers:
      - name: minio
        image: {{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}
        imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.minio.rootUser | quote }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ .Values.minio.rootPassword | quote }}
        ports:
        - name: api
          containerPort: 9000
          protocol: TCP
        - name: console
          containerPort: 9001
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: api
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: api
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          {{- toYaml .Values.minio.resources | nindent 10 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: simpipe-minio
{{- end }}
