apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simpipeController.fullname" . }}
  labels:
    {{- include "simpipeController.labels" . | nindent 4 }}
type: Opaque
data:
  minioAccessKey: {{ .Values.controller.minio.accessKey | b64enc | quote }}
  minioSecretKey: {{ .Values.controller.minio.secretKey | b64enc | quote }}