{{- if .Values.carbontracker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simpipeCarbontracker.serviceAccountName" . }}
  labels:
    {{- include "simpipeCarbontracker.labels" . | nindent 4 }}
  {{- with .Values.carbontracker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}