apiVersion: v1
kind: Service
metadata:
  name: {{ include "simpipeCarbontracker.fullname" . }}
  labels:
    {{- include "simpipeCarbontracker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.carbontracker.service.type }}
  ports:
    - port: {{ .Values.carbontracker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simpipeCarbontracker.selectorLabels" . | nindent 4 }}
