apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simpipeController.serviceAccountName" . }}
  labels:
    {{- include "simpipeController.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
