{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "name", "label": "name" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IO read/writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Reads {{name}} - {{device}}"
    },
    {
     "expr": "rate(container_fs_writes_total{name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Writes {{name}} - {{ device }}"
    }
   ]
  },
  {
   "title": "IOs bytes read/writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Reads {{name}}"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Writes {{name}}"
    }
   ]
  },
  {
   "title": "Network bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Received - {{name}} - {{interface}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Transmit - {{name}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Network packets/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Received - {{name}} - {{interface}}"
    },
    {
     "expr": "rate(container_network_transmit_packets_total{name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Transmit - {{name}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"$name\"}",
     "legendFormat": "{{name}} - {{cpu}}"
    }
   ]
  }
 ]
}