apiVersion: v2
name: simpipe
description: SIMPIPE on Kubernetes
type: application
version: 3.0.0
appVersion: "3.0.0"
dependencies:
  - name: cadvisor
    version: "2.2.4"
    repository: https://ckotzbauer.github.io/helm-charts
    condition: cadvisor.enabled
  - name: prometheus
    version: "19.7.2"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: promscale
    version: "15.0.0"
    repository: https://charts.timescale.com
    condition: promscale.enabled
  - name: kube-prometheus-stack
    version: "45.7.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
  - name: argo-workflows
    version: "0.22.13"
    repository: https://argoproj.github.io/argo-helm
    condition: argo-workflows.enabled
  - name: argo-events
    version: "2.1.3"
    repository: https://argoproj.github.io/argo-helm
    condition: argo-events.enabled
  - name: minio
    version: "12.1.12"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: docker-registry
    version: "2.2.2"
    repository: https://helm.twun.io
    condition: docker-registry.enabled
  - name: sftpgo
    version: "0.14.2"
    repository: https://charts.sagikazarmark.dev
    condition: sftpgo.enabled
  - name: timescaledb
    version: "0.1.0"
    condition: timescaledb.enabled
