apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timescaledb-simple.fullname" . }}
  labels:
    {{- include "timescaledb-simple.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}