kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-ready
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'DoesNotExist'
      - key: '.status.podIP'
        operator: 'DoesNotExist'
  next:
    finalizers:
      add:
        - value: 'kwok.x-k8s.io/fake'
    statusTemplate: |
      {{ $now := Now }}

      conditions:
        - lastTransitionTime: {{ $now }}
          status: "True"
          type: Initialized
        - lastTransitionTime: {{ $now }}
          status: "True"
          type: Ready
        - lastTransitionTime: {{ $now }}
          status: "True"
          type: ContainersReady
        {{ range .spec.readinessGates }}
        - lastTransitionTime: {{ $now }}
          status: "True"
          type: {{ .conditionType }}
        {{ end }}

      containerStatuses:
        {{ range .spec.containers }}
        - image: {{ .image }}
          name: {{ .name }}
          ready: true
          restartCount: 0
          state:
            running:
              startedAt: {{ $now }}
        {{ end }}

      initContainerStatuses:
        {{ range .spec.initContainers }}
        - image: {{ .image }}
          name: {{ .name }}
          ready: true
          restartCount: 0
          state:
            terminated:
              exitCode: 0
              finishedAt: {{ $now }}
              reason: Completed
              startedAt: {{ $now }}
        {{ end }}

      hostIP: {{ NodeIPWith .spec.nodeName }}
      podIP: {{ PodIPWith .spec.nodeName ( or .spec.hostNetwork false ) ( or .metadata.uid "" ) ( or .metadata.name "" ) ( or .metadata.namespace "" ) }}
      phase: Running
      startTime: {{ $now }}
---
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-complete
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'DoesNotExist'
      - key: '.status.phase'
        operator: 'In'
        values:
          - 'Running'
      - key: '.metadata.ownerReferences.[].kind'
        operator: 'In'
        values:
          - 'Workflow'
  next:
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      containerStatuses:
        {{ range $index, $item := .spec.containers }}
        {{ $origin := index $root.status.containerStatuses $index }}
        - image: {{ $item.image }}
          name: {{ $item.name }}
          ready: false
          restartCount: 0
          started: false
          state:
            terminated:
              exitCode: 0
              finishedAt: '{{ $now }}'
              reason: Completed
              startedAt: '{{ $now }}'
        {{ end }}
      phase: Succeeded
---
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-delete
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'Exists'
  next:
    finalizers:
      empty: true
    delete: true
