apiVersion: v2
appVersion: 0.17.0
description: Promscale Connector deployment
home: https://github.com/timescale/promscale
maintainers:
- email: support@timescale.com
  name: TimescaleDB
name: promscale
sources:
- https://github.com/timescale/promscale
- https://github.com/timescale/helm-charts
version: 15.0.0
