apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.simpipe.sct.sintef.no
spec:
  group: simpipe.sct.sintef.no
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectName:
                  type: string
  scope: Namespaced
  names:
    plural: projects
    singular: project
    kind: Project
    shortNames:
      - pj
