- name: Set iptables alternatives for WSL2
  hosts: all
  tasks:
    - name: Check if WSL2 is running
      ansible.builtin.shell: |
        cat /proc/version | grep -q Microsoft && echo true || echo false
      register: is_wsl2
      changed_when: false

    - name: Set iptables to legacy version
      ansible.builtin.command: update-alternatives --set iptables /usr/sbin/iptables-legacy
      when: is_wsl2.stdout == "true"

    - name: Set ip6tables to legacy version
      ansible.builtin.command: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      when: is_wsl2.stdout == "true"
