- name: Install Socat
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600 # 1 hour
    - name: Install socat
      ansible.builtin.apt:
        pkg:
          - socat
