- name: Install K3S
  hosts: all
  vars:
    k3s_build_cluster: false
    k3s_install_hard_links: true
    k3s_become: true
    k3s_server:
      docker: true
      disable:
        - traefik
  roles:
    - xanmanning.k3s
  tasks:
    - name: Setup KUBECONFIG globally
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
        state: present
        create: false
