spectaql:
  logoFile: ../../../docs/logo/sim-pipe_logo.png
  displayAllServers: true

introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile: ../src/server/schema.graphql
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: SIM-PIPE API Reference
  description: |
    This is the reference documentation for the SIM-PIPE API which is implemented using GraphQL.
    The API is authenticated and user authentication is managed using keycloak.<br>
    The URL for token retrieval is "https://datacloud-auth.euprojects.net/auth/realms/user-authentication/protocol/openid-connect/token".<br><br>
    More documentation on how to query a GraphQL API can be found <a href="https://graphql.org/learn/queries/">here</a>.

    Some tutorials for GraphQL beginners are also listed below:<br>
    <ul>
      <li> <a href="https://stepzen.com/docs/using-graphql/graphql-query-basics">GraphQL Query Basics</a> </li>
      <li> <a href="https://hasura.io/learn/graphql/intro-graphql/graphql-queries/">GraphQL Queries - Fetching data</a> </li>
    </ul>
  contact:
    name: Antoine Pultier, Gøran Svaland, Aleena Thomas, Nikolay Nikolov
    email: antoine.pultier@sintef.no, goran.svaland@sintef.no, aleena.thomas@sintef.no, nikolay.nikolov@sintef.no    
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html  

servers:
  - url: http://localhost:8088
    headers:
      - name: Authorization
        example: Bearer <YOUR_TOKEN_HERE>