# SpectaQL is a Node.js library that generates static documentation for a GraphQL schema
# https://github.com/anvilco/spectaql?ref=hackernoon.com

spectaql:
  displayAllServers: true

introspection:
  # removeTrailingPeriodFromDescriptions: false
  schemaFile: src/db/schema.graphql
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: SIM-PIPE API Reference
  description: This provides documentation for the SIM-PIPE API which is implemented using GraphQL.
  # termsOfService: https://www.example.com/terms
  contact:
    name: Antoine Pultier, Aleena Thomas
    # url: http://www.example.com/support
    email: Antoine.Pultier@sintef.no, Aleena.Thomas@sintef.no
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  # x-introItems:
    # - title: Important thing 1
      # description: 

servers:
  - url: http://localhost:9000/graphql
    headers:
      - name: Authorization
        example: Bearer jwt-example