name: Create and publish the frontend docker image

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "*"
  pull_request:
    paths:
      - "frontend/**"

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: datacloud-project/sim-pipe-frontend

jobs:
  build-and-push-frontend-image:
    name: Build and push frontend image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for frontend main image
        id: meta-main
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ steps.meta-main.outputs.tags }}
          labels: ${{ steps.meta-main.outputs.labels }}
          platforms: linux/arm64,linux/amd64
